version: "2"
services:
    rds-restore:
        image: openlmisao/rds-restore:1.0
        volumes:
            - restore-config:/external
        env_file: .env-restore
        depends_on:
          - restore-config

    restore-config:
        build:
            context: ./
        volumes:
          - restore-config:/restore

volumes:
    restore-config:
        external: false
